### PR TITLE
Radio group

### PR DESCRIPTION
**Pull request by nfriedly**
Added a RadioGroup component that extends https://github.com/chenglou/react-radio-group/ with out & a bit of extra opinion (e.g. forces a `<label>` tag)

### CODE REVIEW

**Comment by nfriedly** [comment]
We need to add some margin/padding - the UI component library assumes a space between each DOM element, but react strips out all of the witespace between elements, so it renders like this right now:

screen shot 2016-09-29 at 4 45 28 pm

Any preference on where / how that gets added @jzhang300?

**Comment by nfriedly** [comment]
Default wrapper element is now a `<div>` - you can customize it by setting `Component="span"` on the `<RadioGroup>` and `<Radio>` elements.

Here's what it looks like now:

screen shot 2016-09-30 at 11 20 13 am

**Review by kognate — APPROVED** [review]
Looks good to me.  +1 on editorconfig too.

**Comment by jzhang300** [comment]
@nfriedly The component seems to throw a lot of ESLint issues:
screen shot 2016-09-30 at 10 59 21 am

Also, how come it's `RadioGroup.jsx` as opposed to `RadioGroup.js`?

**Comment by nfriedly** [comment]
> The component seems to throw a lot of ESLint issues:

~~I think you editor might be configured for ES5 instead of ES6 for .jsx files(?)~~ 

My bad.. it turns out eslint just skips .jsx files (at least with out current config). Renaming to .js settled that.

> Also, how come it's RadioGroup.jsx as opposed to RadioGroup.js?

It seemed more correct.. any reason to prefer .js over .jsx?

**Pull request merged**
